"""
Templates for dynamic tool synthesis.
"""

TOOL_PYTHON_TEMPLATE = '''"""
Autogenerated Tool: {tool_name}
Created by: F.R.I.D.A.Y. Tool Forge
Description: {description}
"""

from typing import Any, Dict, List, Optional

def {tool_name}({params_signature}) -> {return_type}:
    """
    {description}
    """
{implementation}
'''

UNITTEST_TEMPLATE = '''import unittest

class TestGeneratedTool(unittest.TestCase):
    def test_basic_execution(self):
{test_cases}
'''
